[build]
  publish = "server/public"
  command = "npm run build || echo 'No build script found'"

[build.environment]
  NODE_VERSION = "18"

# Specific routes should be matched first
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/ready"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/alive"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/health/detailed"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Root path
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Catch-all for all other paths - this should be LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/auth/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/health"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/ready"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/alive"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"